AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: macovidvaccines

Parameters:
  Environment:
    Type: String
    Description: Which environment do you want to deploy to? (stage or prod)
    AllowedValues:
      - stage
      - prod
    Default: stage

Globals:
  Function:
    Timeout: 180

Resources:
  MACovidVaccinesHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Sub "${Environment}"
      CorsConfiguration:
        AllowMethods:
          - DELETE
          - GET
          - HEAD
          - PATCH
          - POST
          - PUT
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowOrigins:
          - "*"

  MACovidVaccineScraper:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "MACovidVaccineScraperFunction-${Environment}"
      Handler: main.handler
      MemorySize: 2048
      Timeout: 180
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy
      Events:
        ScraperSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  MACovidVaxHelpPhoneIntakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "MACovidVaxHelpPhoneIntakeFunction-${Environment}"
      PackageType: Image
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MACovidVaxHelpBotPhoneIntakeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MACovidVaxHelpHttpApi
            Method: POST
            Path: /phone_intake
    Metadata:
      DockerTag: python3.8-v1
      DockerContext: ./
      Dockerfile: PhoneIntake.Dockerfile

  MACovidVaxHelpFullIntakeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "MACovidVaxHelpFullIntakeFunction-${Environment}"
      PackageType: Image
      Policies:
        - AWSLambdaBasicExecutionRole
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - sg-57b02725
        SubnetIds:
          - subnet-02d798c9e00ce3e8c
          - subnet-0c20295596c392c41
          - subnet-0794326484e5570fa
      Events:
        MACovidVaxHelpBotFullIntakeApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MACovidVaxHelpHttpApi
            Method: POST
            Path: /full_intake
    Metadata:
      DockerTag: python3.8-v1
      DockerContext: ./
      Dockerfile: FullIntake.Dockerfile

  MACovidVaxHelpCancelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "MACovidVaxHelpCancelFunction-${Environment}"
      PackageType: Image
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        MACovidVaxHelpBotCancelApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref MACovidVaxHelpHttpApi
            Method: POST
            Path: /cancel
    Metadata:
      DockerTag: python3.8-v1
      DockerContext: ./
      Dockerfile: Cancel.Dockerfile
