const locationData = {
    data: {
        insuranceCarrierImage: null,
        search: {
            id: "3e8edca4-02ab-42de-8594-112031c872e1",
            searchResponse: {
                nearestState: "MA",
                searchRequestId: "99ddefba-2933-43ae-b5d9-4cc222a44312",
                providerLocations: [
                    {
                        id:
                            "pr_BDBebslqJU2vrCAvVMhYeh|lo_zDtK7NZWO0S_rgUqjxD1hB",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_BDBebslqJU2vrCAvVMhYeh",
                            monolithId: "313444",
                            approvedFullName:
                                "Holtzman Medical Group - Mount Ida Campus",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d1k13df5m14swc.cloudfront.net/photos/Holtzman-Medical-Group---Mount-Ida-Campus-313444-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "Holtzman Medical Group",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "- Mount Ida Campus",
                            mayChargeAdditionalCopay: false,
                            nameInSentence:
                                "Holtzman Medical Group - Mount Ida Campus",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl:
                                "/doctor/holtzman-medical-group-mount-ida-campus-313444",
                            frontEndSquarePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/Holtzman-Medical-Group---Mount-Ida-Campus-313444-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_zDtK7NZWO0S_rgUqjxD1hB",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [
                                {
                                    id: "GreatInsuranceCoverage",
                                    title: "Great insurance coverage",
                                    description:
                                        "Accepts a wide range of insurance plans",
                                    imageUrl:
                                        "https://dmr4j5ov2nj36.cloudfront.net/images/selling-points/great_insurance_coverage.svg",
                                    __typename: "SellingPoint",
                                },
                            ],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_zDtK7NZWO0S_rgUqjxD1hB",
                            monolithId: "142090",
                            address1: "777 Dedham St",
                            address2: "",
                            city: "Newton",
                            latitude: 42.298989,
                            longitude: -71.1868746,
                            name: "",
                            phone: "(781) 770-3513",
                            state: "MA",
                            zipCode: "02459",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_xDIn3jylOkWtQ2p1wip1MB",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 23.60351091688029,
                        searchResultId: "5342d691-9b31-4ee5-855c-b22a9760358a",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_CUmBnwtlz0C16bif5EU0IR|lo_X6zHHncQnkqyLp-rvpi1_R",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_CUmBnwtlz0C16bif5EU0IR",
                            monolithId: "312604",
                            approvedFullName: "AFC Springfield",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-Springfield-312604-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "Springfield",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC Springfield",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-springfield-312604",
                            frontEndSquarePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-Springfield-312604-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_X6zHHncQnkqyLp-rvpi1_R",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_X6zHHncQnkqyLp-rvpi1_R",
                            monolithId: "141508",
                            address1: "415 Cooley St",
                            address2: "Unit 3",
                            city: "Springfield",
                            latitude: 42.09149439999999,
                            longitude: -72.49848279999999,
                            name: "AFC Urgent Care Springfield",
                            phone: "(413) 782-4878",
                            state: "MA",
                            zipCode: "01128",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 45.853702047429614,
                        searchResultId: "1e9c668b-a204-431e-802f-f0482df7c811",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_4Vg_3ZeLY0aHJJxsCU-WhB|lo_VA_6br22m02Iu57vrHWtaB",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_4Vg_3ZeLY0aHJJxsCU-WhB",
                            monolithId: "312605",
                            approvedFullName: "AFC West Springfield",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d2uur722ua7fvv.cloudfront.net/photos/AFC-West-Springfield-312605-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "West Springfield",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC West Springfield",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-west-springfield-312605",
                            frontEndSquarePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-West-Springfield-312605-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_VA_6br22m02Iu57vrHWtaB",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_VA_6br22m02Iu57vrHWtaB",
                            monolithId: "141509",
                            address1: "18 Union St",
                            address2: "",
                            city: "West Springfield",
                            latitude: 42.1045754,
                            longitude: -72.62022189999999,
                            name: "AFC Urgent Care West Springfield",
                            phone: "(413) 781-0100",
                            state: "MA",
                            zipCode: "01089",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 51.982320928948695,
                        searchResultId: "4753112e-9a6d-49d6-99f0-da152e904f11",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_VUnpWUtg1k2WFBMK8IhZkx|lo_PhFQcSZjdUKZUHp63gDcmx",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_VUnpWUtg1k2WFBMK8IhZkx",
                            monolithId: "312601",
                            approvedFullName: "AFC Dedham",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-Dedham-312601-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "Dedham",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC Dedham",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-dedham-312601",
                            frontEndSquarePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-Dedham-312601-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_PhFQcSZjdUKZUHp63gDcmx",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_PhFQcSZjdUKZUHp63gDcmx",
                            monolithId: "141505",
                            address1: "370 Providence Hwy",
                            address2: "",
                            city: "Dedham",
                            latitude: 42.2508857,
                            longitude: -71.1715177,
                            name: "AFC Urgent Care Dedham",
                            phone: "(781) 461-0200",
                            state: "MA",
                            zipCode: "02026",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 23.23323854071491,
                        searchResultId: "95002e50-f590-43fd-8db7-c1a5dbc56c0f",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_iXjD9x2P-0OrLNoIknFr8R|lo_xmpTUhghfUC2n6cs3ZGHhh",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_iXjD9x2P-0OrLNoIknFr8R",
                            monolithId: "312603",
                            approvedFullName: "AFC Saugus",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d2uur722ua7fvv.cloudfront.net/photos/AFC-Saugus-312603-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "Saugus",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC Saugus",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-saugus-312603",
                            frontEndSquarePictureUrl:
                                "//d2uur722ua7fvv.cloudfront.net/photos/AFC-Saugus-312603-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_xmpTUhghfUC2n6cs3ZGHhh",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_xmpTUhghfUC2n6cs3ZGHhh",
                            monolithId: "141507",
                            address1: "371 Broadway",
                            address2: "",
                            city: "Saugus",
                            latitude: 42.4873542,
                            longitude: -71.0187148,
                            name: "AFC Urgent Care Saugus",
                            phone: "(781) 233-1000",
                            state: "MA",
                            zipCode: "01906",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 37.651678863832664,
                        searchResultId: "23217fb0-91bc-4bc5-a10a-eab0e4d0fc17",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_pEgrY3r5qEuYKsKvc4Kavx|lo_f3k2t812AUa9NTIYJpbuKx",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_pEgrY3r5qEuYKsKvc4Kavx",
                            monolithId: "312606",
                            approvedFullName: "AFC Worcester",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d2uur722ua7fvv.cloudfront.net/photos/AFC-Worcester-312606-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "Worcester",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC Worcester",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-worcester-312606",
                            frontEndSquarePictureUrl:
                                "//d3wnzga3fpd9a.cloudfront.net/photos/AFC-Worcester-312606-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_f3k2t812AUa9NTIYJpbuKx",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_f3k2t812AUa9NTIYJpbuKx",
                            monolithId: "141510",
                            address1: "117A Stafford St",
                            address2: "",
                            city: "Worcester",
                            latitude: 42.2382351,
                            longitude: -71.8450323,
                            name: "AFC Urgent Care Worcester",
                            phone: "(508) 755-4010",
                            state: "MA",
                            zipCode: "01603",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 13.212553176248356,
                        searchResultId: "e2e8df09-44f5-4152-b903-66553ba22d10",
                        __typename: "ProviderLocation",
                    },
                    {
                        id:
                            "pr_TeD-JuoydUKqszEn2ATb8h|lo_jbrpfIgELEWWL2j5d3t6Sh",
                        nextAvailability: {
                            startTime: "",
                            __typename: "Timeslot",
                        },
                        provider: {
                            id: "pr_TeD-JuoydUKqszEn2ATb8h",
                            monolithId: "312602",
                            approvedFullName: "AFC New Bedford",
                            averageRating: null,
                            averageBedsideRating: null,
                            averageWaitTimeRating: null,
                            canHaveAppointments: true,
                            frontEndCirclePictureUrl:
                                "//d1k13df5m14swc.cloudfront.net/photos/AFC-New-Bedford-312602-circle_medium__v1__.png",
                            defaultProcedureId: "5243",
                            firstName: "AFC",
                            isPreview: false,
                            providerBadges: [],
                            lastName: "New Bedford",
                            mayChargeAdditionalCopay: false,
                            nameInSentence: "AFC New Bedford",
                            onlySeesChildren: false,
                            postnominal: "",
                            prenominal: "",
                            profileUrl: "/doctor/afc-new-bedford-312602",
                            frontEndSquarePictureUrl:
                                "//d2uur722ua7fvv.cloudfront.net/photos/AFC-New-Bedford-312602-mediumfixed.jpg",
                            status: 2,
                            relevantSpecialty: {
                                id: "510",
                                name: "COVID-19 Vaccination Facility",
                                __typename: "Specialty",
                            },
                            procedures: [
                                {
                                    id: "5243",
                                    __typename: "Procedure",
                                },
                            ],
                            reviewCount: 0,
                            specialties: [
                                {
                                    id: "510",
                                    name: "COVID-19 Vaccination Facility",
                                    __typename: "Specialty",
                                },
                            ],
                            visitTypesByState: {
                                allVisitTypes: [],
                                inPersonVisitOnly: ["MA"],
                                virtualVisitOnly: [],
                                __typename: "VisitTypesAvailableByState",
                            },
                            locations: [
                                {
                                    id: "lo_jbrpfIgELEWWL2j5d3t6Sh",
                                    state: "MA",
                                    isVirtual: false,
                                    __typename: "Location",
                                },
                            ],
                            sellingPoints: [],
                            isTopRebookingProvider: false,
                            highlyRecommendPercentage: null,
                            lowWaitTimedPercentage: null,
                            hasNewPatientAvailability: false,
                            __typename: "Provider",
                        },
                        location: {
                            id: "lo_jbrpfIgELEWWL2j5d3t6Sh",
                            monolithId: "141506",
                            address1: "119 Coggeshall St",
                            address2: "",
                            city: "New Bedford",
                            latitude: 41.6565816,
                            longitude: -70.92128890000001,
                            name: "AFC Urgent Care New Bedford",
                            phone: "(508) 990-1900",
                            state: "MA",
                            zipCode: "02746",
                            isVirtual: false,
                            virtualVisitType: "None",
                            __typename: "Location",
                        },
                        practice: {
                            id: "pt_Fc_TLEwEQk-3eisGpsQe-B",
                            isUrgentCare: false,
                            __typename: "Practice",
                        },
                        acceptsInsurance: false,
                        distance: 49.6672484287145,
                        searchResultId: "08388681-360a-40aa-a6e4-2cc6b8161984",
                        __typename: "ProviderLocation",
                    },
                ],
                providerLocationsMapDots: [],
                governmentInsuranceData: null,
                totalCount: 7,
                searchUrl:
                    "https://api-private.east.zocdoccloud.com/search/covid-vaccine/v1/directories/-1/provider-locations?address=MA&caller_type=vaccineSearch&facets=procedures%2Cspecialties%2Csex%2Chospital_affiliations%2Clanguages%2Csees_children%2Ctime_of_day%2Cday_availability&filter=procedures%3A5243&flavor=state-search&state=MA&location_type=placemark&insurance_program_type_name=Unknown&is_premium_eligible_insurance=true&item_offset=0&location=42.4072107%2C-71.3824374&page=0&page_id=b565336407bac4858182249cf30f2f62&page_size=17&procedure_id=5243&rank_by=Default&search_query_guid=b1e737c6-840e-4be5-a367-650b7ac81fd5&specialty_id=510&visit_type=inPersonVisit&virtual_locations_page_size=7",
                insuranceCounts: {
                    inNetwork: null,
                    outOfNetwork: null,
                    __typename: "InsuranceCounts",
                },
                __typename: "SearchResponse",
            },
            searchOrigin: {
                latitude: 42.16115934285715,
                longitude: -71.60887614285714,
                __typename: "SearchCoordinates",
            },
            highlightedProviderLocations: [],
            __typename: "SearchResult",
        },
    },
};

module.exports = {
    locationData,
};
