name: Workflow 1 - Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Install chromium browser
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install chromium-browser
      - name: Set timezone to America/New_York
        run: sudo timedatectl set-timezone America/New_York
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_FAUNA_DB_DEV: ${{ secrets.FAUNA_DB_DEV }}
      - run: npm ci
      # todo: if FAUNA_DB_DEV isn't set, don't run the fauna tests
      - name: Run test suite
        env:
          DEVELOPMENT: true
          CHROMEPATH: /usr/bin/chromium-browser
        run: npm test
      - run: npx prettier --check ./
      - run: npm run verifyLockfile
      - name: Trigger next workflow (this only happens on the default branch, master)
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-2
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
