const sites = [
    {
        name: "Natick Mall",
        street: "1235 Worcester St.",
        city: "Natick",
        zip: "01760",
        signUpLink: "https://home.color.com/vaccine/register/natickmall",
        siteUrl: "Natick%20Mall",
    },
    {
        name: "Gillette Stadium - East",
        street: "1 Patriot Pl.",
        city: "Foxborough",
        zip: "02035",
        signUpLink: "https://home.color.com/vaccine/register/gillettestadium",
        siteUrl: "Gillette%20Stadium%20-%20East",
    },
    {
        name: "Gillette Stadium - West",
        street: "1 Patriot Pl.",
        city: "Foxborough",
        zip: "02035",
        signUpLink: "https://home.color.com/vaccine/register/gillettestadium",
        siteUrl: "Gillette%20Stadium%20-%20West",
    },
    {
        name: "Reggie Lewis State Track Athletic Center",
        street: "1350 Tremont St.",
        city: "Roxbury",
        zip: "02120",
        signUpLink: "https://home.color.com/vaccine/register/reggielewis",
        siteUrl: "Reggie%20Lewis%20Center",
    },
    {
        name: "Hynes Convention Center",
        siteUrl: "Hynes%20Convention%20Center",
        street: "900 Boylston St.",
        city: "Boston",
        zip: "02115",
        signUpLink: "https://home.color.com/vaccine/register/fenway-hynes",
    },
    {
        name: "South Lawrence East School",
        siteUrl: "South%20Lawrence%20East%20School",
        street: "165 Crawford St.",
        city: "Lawrence",
        zip: "01843",
        signUpLink: "https://home.color.com/vaccine/register/lawrencegeneral",
    },
    {
        name: "City of Lawrence Mobile Unit",
        siteUrl: "City%20of%20Lawrence%20Mobile%20Unit",
        city: "Lawrence",
        zip: "01843",
        signUpLink: "https://home.color.com/vaccine/register/lawrencegeneral",
    },
    {
        name: "Chelsea Senior Center",
        siteUrl: "Chelsea",
        calendarUrl: "2dfd243c-7a86-4739-8532-37b344c00ab5",
        street: "10 Riley Way",
        city: "Chelsea",
        zip: "02150",
        signUpLink: "https://www.cic-health.com/chelsea/seniorcenter",
    },
    {
        name: "Hervey Tichon",
        siteUrl: "New%20Bedford",
        calendarUrl: "b9775d3f-e803-442d-a976-4ec9a9073578",
        street: "40 Hervey Tichon Ave",
        city: "New Bedford",
        zip: "02740",
        signUpLink: "https://www.cic-health.com/newbedford/herveytichon",
    },
    {
        name: "Niagara/Maplewood Senior Center",
        siteUrl: "Fall%20River",
        calendarUrl: "233ae909-a088-4565-b418-58d8ee4ecae3",
        street: "550 Tucker Street",
        city: "Fall River",
        zip: "02723",
        signUpLink: "https://www.cic-health.com/fallriver/niagara",
    },
    {
        name: "Fonseca Elementary School",
        siteUrl: "Fall%20River",
        calendarUrl: "b0c30a88-14ba-4bc4-8c84-a56a305bc906",
        street: "160 Wall Street",
        city: "Fall River",
        zip: "02723",
        signUpLink: "https://www.cic-health.com/fallriver/niagara",
    },
    {
        name: "Rumney Marsh Academy",
        siteUrl: "Revere",
        calendarUrl: "7f6e2ddb-08b1-4471-8e15-8ef27897e1ed",
        street: "140 American Legion Hwy",
        city: "Revere",
        zip: "02151",
        signUpLink: "https://www.cic-health.com/revere/rumneymarsh",
    },
    {
        name: "White Stadium",
        siteUrl: "Boston",
        calendarUrl: "e4c71c26-fcc4-43bd-b5ec-2f8ac10468d0",
        street: "450 Walnut Ave",
        city: "Boston",
        zip: "02130",
        signUpLink: "https://www.cic-health.com/boston/whitestadium",
    },
    {
        name: "Jackson/Mann K-8 School Auditorium",
        siteUrl: "Boston",
        calendarUrl: "f56f933d-cdb9-4496-b59a-748896083805",
        street: "500 Cambridge St",
        city: "Allston",
        zip: "02134",
        signUpLink: "https://www.cic-health.com/boston/jacksonmann",
    },
    {
        name: "Wang YMCA of Chinatown",
        siteUrl: "Boston",
        calendarUrl: "f56f933d-cdb9-4496-b59a-748896083805",
        street: "8 Oak St W",
        city: "Boston",
        zip: "02116",
        signUpLink: "https://www.cic-health.com/boston/wang",
    },
    {
        name: "Plumbers & Gasfitters UA Local 12",
        siteUrl: "Boston",
        calendarUrl: "4bc23324-b420-4325-97d2-aa00743f6dc8",
        street: "1240 Massachusetts Ave",
        city: "Dorchester",
        zip: "02125",
        signUpLink: "https://www.cic-health.com/boston/plumbers",
    },
    {
        name: "Iron Workers Local 7 Union",
        siteUrl: "Boston",
        calendarUrl: "b7fa4757-5167-41eb-8626-376fa61fd171",
        street: "195 Old Colony Ave",
        city: "Boston",
        zip: "02127",
        signUpLink: "https://www.cic-health.com/boston/iron",
    },
    {
        name: "Veronica Robles Cultural Center",
        siteUrl: "Boston",
        calendarUrl: "ddb6f50b-9622-4dda-8579-fcc2952f6acf",
        street: "282 Meridian St",
        city: "Boston",
        zip: "02128",
        signUpLink: "https://www.cic-health.com/boston/veronica",
    },
    {
        name: "Tufts University",
        siteUrl: "Tufts%20University",
        street: "161 College Ave",
        city: "Medford",
        zip: "02144",
        signUpLink: "https://home.color.com/vaccine/register/metronorth",
    },
    {
        name: "Encore Boston Harbor",
        siteUrl: "Encore%20Boston%20Harbor",
        street: "1 Broadway Center",
        city: "Everett",
        zip: "02149",
        signUpLink: "https://home.color.com/vaccine/register/metronorth",
    },
    {
        name: "CHA Somerville",
        siteUrl: "CHA%20Somerville",
        street: "176 Somerville Ave",
        city: "Somerville",
        zip: "02143",
        signUpLink: "https://home.color.com/vaccine/register/metronorth",
    },
    {
        name: "Cape Cod Community College",
        siteUrl: "Cape%20Cod%20Community%20College",
        street: "2240 Iyannough Rd",
        city: "West Barnstable",
        zip: "02668",
        signUpLink: "https://home.color.com/vaccine/register/barnstable",
    },
    {
        name: "Orleans DPW",
        siteUrl: "Orleans%20DPW",
        street: "40 Giddiah Hill Rd",
        city: "Orleans",
        zip: "02653",
        signUpLink: "https://home.color.com/vaccine/register/barnstable",
    },
    {
        name: "Barnstable County Fairgrounds",
        siteUrl: "Barnstable%20County%20Fairgrounds",
        street: "1220 Nathan Ellis Hwy",
        city: "East Falmouth",
        zip: "02536",
        signUpLink: "https://home.color.com/vaccine/register/barnstable",
    },
    {
        name: "Converse Middle School",
        siteUrl: "Converse%20Middle%20School",
        street: "24 Converse Street",
        city: "Palmer",
        zip: "01069",
        signUpLink: "https://home.color.com/vaccine/register/palmer",
    },
    {
        name: "Somerset Fire Department",
        siteUrl: "Somerset%20Fire%20Department",
        street: "475 County St",
        city: "Somerset",
        zip: "02726",
        signUpLink: "https://home.color.com/vaccine/register/somersetswansea",
    },
];

module.exports = sites;
